CREATE OR REPLACE USER snowman
PASSWORD = 'sn0wf@ll'
LOGIN_NAME = 'snowstorm'
FIRST_NAME = 'Snow'
LAST_NAME = 'Storm'
EMAIL = 'snow.storm@snowflake.com'
MUST_CHANGE_PASSWORD = true
DEFAULT_WAREHOUSE = COMPUTE_WH;

USE ROLE SECURITYADMIN;

GRANT ROLE SYSADMIN TO USER snowman;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;

SHOW USERS;

SHOW ROLES;

DROP USER snowman;